# Generated by Django 2.1.2 on 2018-10-06 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('primary_name', models.CharField(db_index=True, max_length=500)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveIntegerField(blank=True, null=True)),
                ('primary_profession', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=3)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('title_type', models.CharField(max_length=100)),
                ('primary_title', models.CharField(max_length=500)),
                ('original_title', models.CharField(max_length=500)),
                ('is_adult', models.BooleanField()),
                ('start_year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('runtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), db_index=True, null=True, size=3)),
            ],
        ),
        migrations.AddField(
            model_name='name',
            name='known_for_titles',
            field=models.ManyToManyField(to='nozbe.Title'),
        ),
    ]
